"""add nationality to blacklist

Revision ID: 943b302c3a23
Revises: cf337d047910
Create Date: 2025-06-25 13:43:24.776207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943b302c3a23'
down_revision: Union[str, None] = 'cf337d047910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist', sa.Column('nationality', sa.Enum('KZ', 'FOREIGN', name='nationalitytype'), nullable=True))
    op.add_column('blacklist', sa.Column('iin', sa.String(length=12), nullable=True))
    op.alter_column('blacklist', 'doc_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('blacklist', 'doc_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('blacklist', 'citizenship',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('blacklist', 'company',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_blacklist_doc_number'), 'blacklist', ['doc_number'], unique=False)
    op.create_index(op.f('ix_blacklist_iin'), 'blacklist', ['iin'], unique=False)
    op.drop_column('blacklist', 'doc_end_date')
    op.drop_column('blacklist', 'doc_start_date')
    op.add_column('request_persons', sa.Column('nationality', sa.Enum('KZ', 'FOREIGN', name='nationalitytype'), server_default='KZ', nullable=False))
    op.add_column('request_persons', sa.Column('iin', sa.String(length=12), nullable=True))
    op.alter_column('request_persons', 'doc_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('request_persons', 'doc_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('request_persons', 'doc_start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('request_persons', 'doc_end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_request_persons_doc_number'), 'request_persons', ['doc_number'], unique=False)
    op.create_index(op.f('ix_request_persons_iin'), 'request_persons', ['iin'], unique=False)
    op.add_column('visit_logs', sa.Column('checkpoint_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'visit_logs', 'checkpoints', ['checkpoint_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit_logs', type_='foreignkey')
    op.drop_column('visit_logs', 'checkpoint_id')
    op.drop_index(op.f('ix_request_persons_iin'), table_name='request_persons')
    op.drop_index(op.f('ix_request_persons_doc_number'), table_name='request_persons')
    op.alter_column('request_persons', 'doc_end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('request_persons', 'doc_start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('request_persons', 'doc_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('request_persons', 'doc_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('request_persons', 'iin')
    op.drop_column('request_persons', 'nationality')
    op.add_column('blacklist', sa.Column('doc_start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('blacklist', sa.Column('doc_end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_blacklist_iin'), table_name='blacklist')
    op.drop_index(op.f('ix_blacklist_doc_number'), table_name='blacklist')
    op.alter_column('blacklist', 'company',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blacklist', 'citizenship',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blacklist', 'doc_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blacklist', 'doc_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('blacklist', 'iin')
    op.drop_column('blacklist', 'nationality')
    # ### end Alembic commands ###
