"""empty message

Revision ID: b6645051f017
Revises: 943b302c3a23
Create Date: 2025-06-26 18:08:10.202100

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6645051f017"
down_revision: Union[str, None] = "943b302c3a23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for val in [
        "PENDING_USB",
        "APPROVED_USB",
        "DECLINED_USB",
        "PENDING_AS",
        "APPROVED_AS",
        "DECLINED_AS",
    ]:
        op.execute(f"ALTER TYPE requestpersonstatus ADD VALUE IF NOT EXISTS '{val}';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
