"""STATUS for RequestPerson

Revision ID: cf337d047910
Revises: fad03f5a5dfc
Create Date: 2025-06-24 16:57:06.635115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf337d047910'
down_revision: Union[str, None] = 'fad03f5a5dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_persons', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requestpersonstatus'), server_default='PENDING', nullable=False))
    op.add_column('request_persons', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('visit_logs', sa.Column('request_person_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('visit_logs_user_id_fkey'), 'visit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'visit_logs', 'request_persons', ['request_person_id'], ['id'])
    op.drop_column('visit_logs', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visit_logs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'visit_logs', type_='foreignkey')
    op.create_foreign_key(op.f('visit_logs_user_id_fkey'), 'visit_logs', 'users', ['user_id'], ['id'])
    op.drop_column('visit_logs', 'request_person_id')
    op.drop_column('request_persons', 'rejection_reason')
    op.drop_column('request_persons', 'status')
    # ### end Alembic commands ###
